//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bnd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bnd()
        {
            this.Orders = new HashSet<Order>();
            this.SubBnds = new HashSet<SubBnd>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<double> TotalNum { get; set; }
        public Nullable<double> AfterReductionNum { get; set; }
        public Nullable<double> Month1Share { get; set; }
        public Nullable<double> Month2Share { get; set; }
        public Nullable<double> Month3Share { get; set; }
        public Nullable<double> Month4Share { get; set; }
        public Nullable<double> Month5Share { get; set; }
        public Nullable<double> Month6Share { get; set; }
        public Nullable<double> Month7Share { get; set; }
        public Nullable<double> Month8Share { get; set; }
        public Nullable<double> Month9Share { get; set; }
        public Nullable<double> Month10Share { get; set; }
        public Nullable<double> Month11Share { get; set; }
        public Nullable<double> Month12Share { get; set; }
        public Nullable<double> Month13Share { get; set; }
        public string Unit { get; set; }
        public Nullable<double> PeriodOnMonth { get; set; }
        public Nullable<double> PercentOfCostChargedtoProject { get; set; }
        public string BudgetLineItem { get; set; }
        public Nullable<int> NumberOfUnits { get; set; }
        public Nullable<double> PerUnitCost { get; set; }
        public string Simbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubBnd> SubBnds { get; set; }
    }
}
