//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Bnd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bnd()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «”„ «·»‰œ")]
        [DisplayName("«”„ «·»‰œ")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·—ﬁ„ «·ﬂ·Ì")]
        [DisplayName("«·—ﬁ„ «·ﬂ·Ì")]
        public Nullable<int> TotalNum { get; set; }
        [DisplayName("«·—ﬁ„ »⁄œ «· Œ›Ì÷")]
        public Nullable<int> AfterReductionNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
