//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Center
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Center()
        {
            this.Centers1 = new HashSet<Center>();
            this.Employees = new HashSet<Employee>();
            this.Lessons = new HashSet<Lesson>();
            this.Orders = new HashSet<Order>();
            this.Prooves = new HashSet<Proove>();
            this.Students = new HashSet<Student>();
            this.SubBnds = new HashSet<SubBnd>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «”„ «·„—ﬂ“")]
        [DisplayName("«”„ «·„—ﬂ“")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·„Êﬁ⁄")]
        [DisplayName("«·„Êﬁ⁄")]
        public string Place { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·‘—Õ")]
        [DisplayName("«·‘—Õ")]
        public string Desc { get; set; }
        [DisplayName("«·Õ«·…")]
        public string State { get; set; }
        [Range(2, int.MaxValue, ErrorMessage = "Ì—ÃÏ «œŒ«· —ﬁ„ √⁄·Ï „‰ 2")]
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· ⁄œœ «·’›Ê’")]
        [DisplayName("⁄œœ «·’›Ê’")]
        public Nullable<int> HolesN { get; set; }
        public Nullable<int> Cityid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· ‰Ê⁄ «·„‰‘«…")]
        [DisplayName("‰Ê⁄ «·„‰‘«…")]
        public string FoundationType { get; set; }
        public Nullable<int> Periodid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· „·«ÕŸ« ")]
        [DisplayName("„·«ÕŸ« ")]
        public string Notes { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·„«·ﬂ")]
        [DisplayName("«·„«·ﬂ")]
        public string Owner { get; set; }
        public Nullable<bool> Month10 { get; set; }
        public Nullable<bool> Month11 { get; set; }
        public Nullable<bool> Month12 { get; set; }
        public Nullable<bool> Month1 { get; set; }
        public Nullable<bool> Month2 { get; set; }
        public Nullable<bool> Month3 { get; set; }
        public Nullable<bool> Month4 { get; set; }
        public Nullable<bool> Month5 { get; set; }
        public Nullable<bool> Month6 { get; set; }
        public Nullable<bool> Month7 { get; set; }
        public Nullable<bool> Month8 { get; set; }
        public Nullable<bool> Month9 { get; set; }
        [DisplayName("«·› Ì«‰")]
        public Nullable<int> TargetedMen { get; set; }
        [DisplayName("«·› Ì« ")]
        public Nullable<int> TargetedWomen { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· ‰Ê⁄ «·„—ﬂ“")]
        [DisplayName("‰Ê⁄ «·„—ﬂ“")]
        public string CenterType { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·œ›⁄ «·‘Â—Ì")]
        [DisplayName("«·œ›⁄ «·‘Â—Ì")]
        public Nullable<int> MonthlyPayment { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·œ›⁄ «·—»⁄Ì")]
        [DisplayName("«·œ›⁄ «·—»⁄Ì")]
        public Nullable<int> QuarterPayment { get; set; }
        public string Proof { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> DependedOn { get; set; }
        [DisplayName(" «—ÌŒ «·«÷«›…")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> AddingDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        [DisplayName("“„‰ «·«÷«›…")]
        public Nullable<System.TimeSpan> AddingTime { get; set; }
        public Nullable<double> SpentBudget { get; set; }
        public Nullable<int> PCenterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Center> Centers1 { get; set; }
        public virtual Center Center1 { get; set; }
        public virtual City City { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Period Period { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proove> Prooves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubBnd> SubBnds { get; set; }
    }
}
