//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.Centers = new HashSet<Center>();
            this.Employees = new HashSet<Employee>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·„œÌ‰…")]
        [DisplayName("«·„œÌ‰…")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·œÊ·…")]
        [DisplayName("«·œÊ·…")]
        public string CountryName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<System.TimeSpan> AddingTime { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Center> Centers { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
