//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int id { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Manager { get; set; }
        public Nullable<bool> CoManager { get; set; }
        public Nullable<bool> SchoolManager { get; set; }
        public Nullable<bool> NormalEmployee { get; set; }
        public Nullable<bool> AddNewEmployeeType { get; set; }
        public Nullable<bool> AddNewProject { get; set; }
        public Nullable<bool> AddBuyingRequest { get; set; }
        public Nullable<bool> AddManagers { get; set; }
        public Nullable<bool> AddCOManagers { get; set; }
        public Nullable<bool> AddSchoolManagers { get; set; }
        public Nullable<bool> AddSchoolEmployees { get; set; }
        public Nullable<bool> AddCitesAndCenters { get; set; }
        public Nullable<bool> AddSchoolManagingTools { get; set; }
        public Nullable<bool> AddDaileyReport { get; set; }
        public Nullable<bool> AddExam { get; set; }
        public Nullable<bool> ApproveExam { get; set; }
        public Nullable<bool> AddPresence { get; set; }
        public Nullable<bool> AddStudent { get; set; }
        public Nullable<bool> Finance { get; set; }
        public Nullable<bool> HighAcceptance { get; set; }
        public Nullable<bool> BuyingAcceptance { get; set; }
        public Nullable<bool> SeeAll { get; set; }
        public Nullable<bool> SeeAllButFinance { get; set; }
        public Nullable<bool> SeeAccToCity { get; set; }
        public Nullable<bool> SeeAccToCenter { get; set; }
        public Nullable<bool> SeeTeachers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
