//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.Prooves = new HashSet<Proove>();
        }
    
        public int id { get; set; }
        public Nullable<int> ExamTypeid { get; set; }
        public Nullable<double> Mark { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Subjectid { get; set; }
        public Nullable<int> Studentid { get; set; }
        public Nullable<int> Stageid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Proof { get; set; }
    
        public virtual ExamType ExamType { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Student Student { get; set; }
        public virtual Study_subject Study_subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proove> Prooves { get; set; }
    }
}
