//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int id { get; set; }
        public string Day { get; set; }
        public string State { get; set; }
        public string Lesson1 { get; set; }
        public string Lesson2 { get; set; }
        public string Lesson3 { get; set; }
        public string Lesson4 { get; set; }
        public string Lesson5 { get; set; }
        public string Lesson6 { get; set; }
        public string Lesson7 { get; set; }
        public Nullable<int> Regimentid { get; set; }
        public Nullable<int> Stageid { get; set; }
        public Nullable<int> Periodid { get; set; }
        public Nullable<int> Centerid { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Period Period { get; set; }
        public virtual Regiment Regiment { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
