//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MissionResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MissionResponse()
        {
            this.MissionResponse1 = new HashSet<MissionResponse>();
        }
    
        public int id { get; set; }
        public Nullable<int> MissionID { get; set; }
        public Nullable<int> NestedID { get; set; }
        [DisplayName("«· ⁄·Ìﬁ")]
        public string Response { get; set; }
        public Nullable<int> WriterID { get; set; }
        [DisplayName("‰Ê⁄ «· ⁄·Ìﬁ")]
        public string type { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Mission Mission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MissionResponse> MissionResponse1 { get; set; }
        public virtual MissionResponse MissionResponse2 { get; set; }
    }
}
