//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonUserAddRequest
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string FathersName { get; set; }
        public string Certificate { get; set; }
        public string CType { get; set; }
    }
}
