//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NonUserAddRequest
    {
        public int id { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá ÇáäæÚ ")]
        [DisplayName("ÇáäæÚ")]
        public string Type { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá ÇáÇÓã ")]
        [DisplayName("ÇáÇÓã")]
        public string Name { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá ÇáßäíÉ ")]
        [DisplayName("ÇáßäíÉ")]
        public string Surname { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá ÑŞã ÇáåÇÊİ ")]
        [DisplayName("ÑŞã ÇáåÇÊİ")]
        public Nullable<int> PhoneNumber { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá ÇÓã ÇáÃÈ ")]
        [DisplayName("ÇÓã ÇáÃÈ")]
        public string FathersName { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá ÇáÔåÇÏÉ ")]
        [DisplayName("ÇáÔåÇÏÉ")]
        public string Certificate { get; set; }
        [Required(ErrorMessage = "íÑÌì ÇÏÎÇá äæÚ ÇáÔåÇÏÉ ")]
        [DisplayName("äæÚ ÇáÔåÇÏÉ")]
        public string CType { get; set; }
    }
}
