//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public Nullable<int> Employeeid { get; set; }
        public Nullable<int> Bndid { get; set; }
        public string Desc { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PeacePrice { get; set; }
        public string State { get; set; }
        public Nullable<bool> FirstLevelSign { get; set; }
        public Nullable<bool> SecondLevelSign { get; set; }
        public Nullable<bool> ThirdLevelSign { get; set; }
        public Nullable<bool> FourthLevelSign { get; set; }
        public Nullable<bool> FifthLevelSign { get; set; }
        public Nullable<bool> SixthLevelSign { get; set; }
        public Nullable<bool> SeventhLevelSign { get; set; }
        public Nullable<bool> EightithLevelSign { get; set; }
        public string Proof { get; set; }
        public Nullable<bool> SendingLevelSign { get; set; }
        public Nullable<bool> RecievingLevelSign { get; set; }
        public Nullable<bool> AfterRecieveFirstLevelSign { get; set; }
        public Nullable<bool> AfterRecieveSecondLevelSign { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> CenterID { get; set; }
    
        public virtual Bnd Bnd { get; set; }
        public virtual Center Center { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
