//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presence
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Desc { get; set; }
        public Nullable<int> Studentid { get; set; }
        public Nullable<bool> Lesson1 { get; set; }
        public Nullable<bool> Lesson2 { get; set; }
        public Nullable<bool> Lesson3 { get; set; }
        public Nullable<bool> Lesson4 { get; set; }
        public Nullable<bool> Lesson5 { get; set; }
        public Nullable<bool> Lesson6 { get; set; }
        public Nullable<bool> Lesson7 { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<System.TimeSpan> AddingTime { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
