//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proove
    {
        public int id { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ExaminationID { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ZipFilePath { get; set; }
        public Nullable<int> MissionID { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual Order Order { get; set; }
        public virtual Student Student { get; set; }
        public virtual Mission Mission { get; set; }
    }
}
