//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Examinations = new HashSet<Examination>();
            this.Presences = new HashSet<Presence>();
            this.Prooves = new HashSet<Proove>();
        }


        public int id { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«·  «—ÌŒ «·Ê·«œ…")]
        [DisplayName(" «—ÌŒ «·Ê·«œ…")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> BDate { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «”„ «·ÿ«·»")]
        [DisplayName("«”„ «·ÿ«·»")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· ﬂ‰Ì… «·ÿ«·»")]
        [DisplayName("ﬂ‰Ì… «·ÿ«·»")]
        public string Surname { get; set; }


        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·‘Â«œ…")]
        [DisplayName("«·‘Â«œ…")]
        public string Certificate { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·⁄·«„…")]
        [DisplayName("«·⁄·«„…")]
        public Nullable<double> Mark { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·Õ«·…")]

        [DisplayName("«·Õ«·…")]
        public string State { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·„—ﬂ“")]

        public Nullable<int> Centerid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·„—Õ·…")]

        public Nullable<int> Stageid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·‘⁄»…")]

        public Nullable<int> Regimentid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«·  «—ÌŒ «·»œ¡")]
        [DisplayName(" «—ÌŒ «·»œ¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> SDate { get; set; }

        [DisplayName(" «—ÌŒ «·«‰ Â«¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> EDate { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· —ﬁ„ «·ÿ«·»")]

        [DisplayName("—ﬁ„ «·ÿ«·»")]
        public Nullable<int> StudentNumber { get; set; }
        [DisplayName("«·«À»« ")]
        public string Proof { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «”„ «·√»")]

        [DisplayName("«”„ «·√»")]
        public string FathersName { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·Ã‰”")]

        [DisplayName("«·Ã‰”")]
        public string Sex { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AddedBy { get; set; }
        [DisplayName(" «—ÌŒ «·«÷«›…")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> AddingDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        [DisplayName("“„‰ «·«÷«›…")]
        public Nullable<System.TimeSpan> AddingTime { get; set; }
        [DisplayName("«·„œ—”… «· Ì ﬂ«‰ Ìœ—” »Â«")]

        public string OldSchool { get; set; }
        [DisplayName("Õ«·… «·ÿ«·»")]

        public string StudentState { get; set; }
        [DisplayName("«”„ «·√„")]

        public string Mothersname { get; set; }
        [DisplayName(" «—ÌŒ «·ﬁ»Ê·")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> ApprovalDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        [DisplayName("“„‰ «·ﬁ»Ê·")]

        public Nullable<System.TimeSpan> ApprovalTime { get; set; }
        [DisplayName("—ﬁ„ «·Â« ›")]

        public Nullable<long> PhoneNumber { get; set; }

        public virtual Center Center { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence> Presences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proove> Prooves { get; set; }
        public virtual Regiment Regiment { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
