//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Examinations = new HashSet<Examination>();
            this.Presences = new HashSet<Presence>();
            this.Prooves = new HashSet<Proove>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Certificate { get; set; }
        public Nullable<double> Mark { get; set; }
        public string State { get; set; }
        public Nullable<int> Centerid { get; set; }
        public Nullable<int> Stageid { get; set; }
        public Nullable<int> Regimentid { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> StudentNumber { get; set; }
        public string Proof { get; set; }
        public string FathersName { get; set; }
        public string Sex { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
        public Nullable<System.TimeSpan> AddingTime { get; set; }
        public string OldSchool { get; set; }
        public string StudentState { get; set; }
        public string Mothersname { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.TimeSpan> ApprovalTime { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence> Presences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proove> Prooves { get; set; }
        public virtual Regiment Regiment { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
