//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SubBnd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubBnd()
        {
            this.Orders = new HashSet<Order>();
        }

        public int id { get; set; }
        public Nullable<int> BndId { get; set; }
        public Nullable<int> CenterID { get; set; }
        [DisplayName("«·„«œ…")]

        public string Subject { get; set; }
        [DisplayName("”⁄— «·ﬁÿ⁄…")]

        public Nullable<double> PeacePrice { get; set; }
        [DisplayName("⁄œœ «·ﬁÿ⁄")]

        public Nullable<int> Quantity { get; set; }
        [DisplayName("«·„Ã„Ê⁄")]

        public Nullable<double> SumPrice { get; set; }
        [DisplayName("«· «—ÌŒ")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]

        public Nullable<System.DateTime> Date { get; set; }

        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> Orderid { get; set; }

        public virtual Bnd Bnd { get; set; }
        public virtual Center Center { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Order Order { get; set; }
    }
}
