//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntensiveLearning.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubBnd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubBnd()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public Nullable<int> BndId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public string Subject { get; set; }
        public Nullable<double> PeacePrice { get; set; }
        public Nullable<double> SumPrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> PayymentApprove { get; set; }
        public Nullable<bool> BuyingApprove { get; set; }
        public string proof { get; set; }
        public Nullable<bool> ProofAcceptance { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Paymentid { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Bnd Bnd { get; set; }
        public virtual Center Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual PaymentsRecord PaymentsRecord { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
